# Generated by Django 3.2 on 2023-08-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
